# Travis bestand voor CheckJeStress

language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: hhvm
    - php: nightly

script: sh travis_parse.sh src
